name: ci

on: [push]

env: 
  NIXPKGS_ALLOW_UNFREE: 1

jobs: 
  lint:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: install flake dependencies
        run: nix develop --impure && nix flake check --impure
      - name: install mix dependencies
        run: nix develop --impure --command mix deps.get
      - name: lint
        run: nix develop --impure --command mix format --check-formatted 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create database
        id: create-database
        uses: ./.github/actions/create-database
        with:
          organization_name: ${{ secrets.TURSO_ORGANIZATION_NAME }}
          group_name: ${{ secrets.TURSO_GROUP_NAME }}
          api_token: ${{ secrets.TURSO_API_TOKEN }}
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: install flake dependencies
        run: nix develop --impure && nix flake check --impure
      - name: install mix dependencies
        run: nix develop --impure --command mix deps.get
      - name: run tests
        run: nix develop --impure --command mix test
        env:
          HOSTNAME: ${{ steps.create-database.outputs.hostname }}
          TOKEN: ${{ steps.create-database.outputs.token }}
      - name: delete database
        if: always()
        uses: ./.github/actions/delete-database
        with:
          organization_name: ${{ secrets.TURSO_ORGANIZATION_NAME }}
          api_token: ${{ secrets.TURSO_API_TOKEN }}

